
//Create a new variable for don't repeat codigo
@apí = http://localhost:4000/ccostos

###List of services (parameter 0) or servcio (parameter id)
GET {{apí}}/0

###Eliminacion por id
DELETE {{apí}}/13

###Insert new servicie
POST {{apí}}
Content-Type: application/json

{
    "iidccosto": 0, 
    "nombre": "Nuevo centro de costos"
}


