
//Create a new variable for don't repeat codigo
@apí = http://localhost:4000/servicios

###List of services (parameter 0) or servcio (parameter id)
GET {{apí}}/0

###Eliminacion por id
DELETE {{apí}}/5

###Insert new servicie
POST {{apí}}
Content-Type: application/json

{
    "iidservicio": 13, //envie 0 para insertar
    "nombre": "Servicio Modificado"
}


